# Generated by Django 3.0.6 on 2020-05-15 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.URLField(max_length=1000)),
                ('datePosted', models.DateTimeField(null=True)),
                ('numberOfComments', models.IntegerField()),
                ('lastPost', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('username', models.TextField()),
                ('datePosted', models.DateTimeField(null=True)),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserCommenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('datePosted', models.DateTimeField(null=True)),
                ('username', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='comments.Article')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='comments.UserCommenter')),
            ],
        ),
    ]
